# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('type', models.TextField()),
                ('Monday', models.TextField()),
                ('Tuesday', models.TextField()),
                ('Wednesday', models.TextField()),
                ('Thursday', models.TextField()),
                ('Friday', models.TextField()),
                ('Saturday', models.TextField()),
                ('Sunday', models.TextField()),
                ('borough', models.TextField()),
                ('zip', models.TextField()),
                ('cell', models.TextField()),
                ('picksup', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
