# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRecycleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialWasteSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('location', models.TextField()),
                ('hours', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
