# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRecycleApp', '0004_auto_20171205_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
