# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRecycleApp', '0005_auto_20171205_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
