# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainRecycleApp', '0006_zips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zips',
            new_name='Zip',
        ),
    ]
