# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainRecycleApp', '0008_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRecyclingBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borough', models.TextField()),
                ('siteType', models.TextField()),
                ('siteName', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
    ]
